// <auto-generated />
using System;
using GharBazar.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GharBazar.API.Migrations
{
    [DbContext(typeof(GharBazarDbContext))]
    [Migration("20260301043903_AddTourBookings")]
    partial class AddTourBookings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GharBazar.API.Models.Message", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("PropertyId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("receiver_id");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sender_id");

                    b.HasKey("MessageId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("GharBazar.API.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notification_id");

                    b.Property<string>("ActionNotes")
                        .HasColumnType("longtext")
                        .HasColumnName("action_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("owner_id");

                    b.Property<string>("PropertyId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertyTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("property_title");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("NotificationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("GharBazar.API.Models.Property", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.Property<string>("Amenities")
                        .HasColumnType("longtext")
                        .HasColumnName("amenities");

                    b.Property<decimal?>("AreaSqft")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("area_sqft");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int")
                        .HasColumnName("bathrooms");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("bedrooms");

                    b.Property<string>("City")
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("ListedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("listed_date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("property_type");

                    b.Property<string>("State")
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("longtext")
                        .HasColumnName("verification_notes");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("verification_status");

                    b.HasKey("PropertyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("properties");
                });

            modelBuilder.Entity("GharBazar.API.Models.PropertyDocument", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("document_name");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("document_type");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("document_url");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_date");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("longtext")
                        .HasColumnName("verification_notes");

                    b.Property<bool>("Verified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("verified");

                    b.HasKey("DocumentId");

                    b.HasIndex("PropertyId");

                    b.ToTable("property_documents");
                });

            modelBuilder.Entity("GharBazar.API.Models.PropertyImage", b =>
                {
                    b.Property<string>("ImageId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.HasKey("ImageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("property_images");
                });

            modelBuilder.Entity("GharBazar.API.Models.Review", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("review_id");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("GharBazar.API.Models.TourBooking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("booking_id");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TourDate")
                        .HasColumnType("date")
                        .HasColumnName("tour_date");

                    b.Property<string>("TourTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tour_time");

                    b.HasKey("BookingId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SellerId");

                    b.ToTable("tour_bookings");
                });

            modelBuilder.Entity("GharBazar.API.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("longtext")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("GharBazar.API.Models.WishlistItem", b =>
                {
                    b.Property<string>("WishlistId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("wishlist_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("property_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("WishlistId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId", "PropertyId")
                        .IsUnique();

                    b.ToTable("wishlist");
                });

            modelBuilder.Entity("GharBazar.API.Models.Message", b =>
                {
                    b.HasOne("GharBazar.API.Models.Property", "Property")
                        .WithMany("Messages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GharBazar.API.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GharBazar.API.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GharBazar.API.Models.Notification", b =>
                {
                    b.HasOne("GharBazar.API.Models.User", "Owner")
                        .WithMany("Notifications")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GharBazar.API.Models.Property", "Property")
                        .WithMany("Notifications")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("GharBazar.API.Models.Property", b =>
                {
                    b.HasOne("GharBazar.API.Models.User", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GharBazar.API.Models.PropertyDocument", b =>
                {
                    b.HasOne("GharBazar.API.Models.Property", "Property")
                        .WithMany("Documents")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("GharBazar.API.Models.PropertyImage", b =>
                {
                    b.HasOne("GharBazar.API.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("GharBazar.API.Models.Review", b =>
                {
                    b.HasOne("GharBazar.API.Models.Property", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GharBazar.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GharBazar.API.Models.TourBooking", b =>
                {
                    b.HasOne("GharBazar.API.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GharBazar.API.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GharBazar.API.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Property");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("GharBazar.API.Models.WishlistItem", b =>
                {
                    b.HasOne("GharBazar.API.Models.Property", "Property")
                        .WithMany("WishlistItems")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GharBazar.API.Models.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GharBazar.API.Models.Property", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Images");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("GharBazar.API.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Properties");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("Reviews");

                    b.Navigation("SentMessages");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
